on:
  issue_comment:
    types: [created]

name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Automatic Rebase
        uses: Paulomart/rebase@test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}
