on:
  pull_request:
    types: [labeled]

name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && github.event.pull_request.label.name == 'needs-rebase'
    runs-on: ubuntu-latest

    steps:
      - name: Debug Action
        uses: hmarr/debug-action@v1.0.0

      - uses: actions/checkout@v1

      - name: Automatic Rebase
        uses: Paulomart/rebase@test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TKN }}
